version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:latest"
    environment:
      - MYSQL_DATABASE=springdata_jpa
      - MYSQL_USER=test
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
    restart: always
    ports:
      - 3307:3306

