server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/springdata_jpa?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: test
    password: supersecret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        use-new-id-generator-mappings: false
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
