server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/springdata_jpa?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: test
    password: "12345678"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      format_sql: true
      ddl-auto: update
      use-new-id-generator-mappings: false
